apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: currency-controller
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/currency-controller:v1
        imagePullPolicy: Always