apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: kafka-consumer
spec:
  consumerGroup: knative-group
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9092
  topics: finance
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display