apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kafka-producer
spec:
  template:
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/kafka-producer:v1
        imagePullPolicy: Always