apiVersion: sources.knative.dev/v1alpha2
kind: SinkBinding
metadata:
  name: currency-sink-bind
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: currency-controller
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: currency-kafka